#!/bin/bash
# Monitor the battery level and send a notification if it falls below 20%.
# Also notify if the battery is fully charged.

ADAPTER_STATUS="/sys/class/power_supply/ADP0/online" # could be different on your system!
STATUS=$(cat $ADAPTER_STATUS)

BATTERY_LEVEL=$(acpi -b | grep -P -o '[0-9]+(?=%)')

DISCHARGE_FILE="/home/bharath/scripts/discharge"
CHARGE_FILE="/home/bharath/scripts/charge"

LOW_CAP=20 # how low is too low?
FULL_CAP=100  # full capacity

DISCHARGING="0"
CHARGING="1"

# Eye Candy

ICON_LOW="/usr/share/icons/gnome/32x32/status/battery-caution.png"
ICON_FULL="/usr/share/icons/gnome/32x32/status/battery-full-charged.png"
ICON_CHARGING="/usr/share/icons/gnome/32x32/status/battery-low-charging.png"
ICON_DISCHARGING="/usr/share/icons/gnome/32x32/status/battery-good.png"

## CASE1, Usual Charging: Any level < 100% AND charging.
if [ $BATTERY_LEVEL -lt $FULL_CAP -a $STATUS -eq $CHARGING ]
then
	if [ ! -f $CHARGE_FILE ]
	then
		notify-send -u low -i $ICON_CHARGING -t 5000 "Battery Charging" "Battery is currently at ${BATTERY_LEVEL}%..."
		if [ -f $DISCHARGE_FILE ]; then rm $DISCHARGE_FILE; fi
		touch $CHARGE_FILE
	fi
fi

## CASE2, Usual Discharging: Any level <=100% AND discharging.
if [ $BATTERY_LEVEL -le $FULL_CAP -a $STATUS -eq $DISCHARGING ]
then
	if [ ! -f $DISCHARGE_FILE ]
	then
		notify-send -u low -i $ICON_DISCHARGING -t 5000 "Battery Discharging" "Battery is currently at ${BATTERY_LEVEL}%."
		if [ -f $CHARGE_FILE ]; then rm $CHARGE_FILE; fi
		touch $DISCHARGE_FILE
	fi
fi

## CASE3, Overcharging: Reach 100% AND charging still.
if [ $BATTERY_LEVEL -eq $FULL_CAP -a $STATUS -eq $CHARGING ]
then
	notify-send -u normal -i $ICON_FULL -t 5000 "Battery Charged" "Battery at 100%.\n You may unplug the charger now."
	if [ -f $CHARGE_FILE ]; then rm $CHARGE_FILE; fi
	if [ -f $DISCHARGE_FILE ]; then rm $DISCHARGE_FILE; fi
fi

## CASE4, Low on charge: Any level <=20% AND discharging still.
if [ $BATTERY_LEVEL -le $LOW_CAP -a $STATUS -eq $DISCHARGING ]
then
	notify-send -u critical -i $ICON_LOW -t 5000 "Battery Low" "Battery level is ${BATTERY_LEVEL}%!"
	if [ -f $DISCHARGE_FILE ]; then rm $DISCHARGE_FILE; fi
fi
